---
title: "COVID-19 ZA"
output: 
  flexdashboard::flex_dashboard:
    self_contained: false
    orientation: rows
    vertical_layout: scroll
    navbar:
      - { title: "painblogR", href: "https://www.painblogr.org", align: right }
    social: [ "twitter", "facebook", "menu" ]
    source_code: "https://github.com/kamermanpr/covid_19_dashboard.git"
---

<style type="text/css">

.chart-title {
  border-bottom: 1px solid #d7d7d7;
  color: #000000;
  font-size: 20px;
  font-weight: 300;
  padding: 7px 10px 4px;
}

</style>

```{r setup, include = FALSE}
# Load libraries
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(sf)
library(ggiraph)
library(plotly)

# Import data
## ZA
data <- read_csv('https://raw.githubusercontent.com/kamermanpr/covid_19_dataZA/master/data.csv')

## World
data_jhu <- read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')

## US extra (missing early data from JHU)
### (No longer needed, JHU updated records)
#data_us <- read_csv('https://raw.githubusercontent.com/kamermanpr/covid_19_dashboard/master/data/us-2020-01-21-to-2020-03-09.csv')

recover_jhu <- read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')

deaths_jhu <- read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')

# knitr options
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

Row {data-height=250}
----------

Welcome to my site, which gives updates on the state of COVID-19 cases and deaths in South Africa. These data are updated daily based on data released by the [National Institute of Communicable Diseases](http://www.nicd.ac.za/){target="_blank"}, and [Johns Hopkins University Coronavirus Resource Center](https://coronavirus.jhu.edu/map.html){target="_blank"}. For the moment, the site reports on: **i)** the cumulative number of cases in the South Africa and each of its provinces (Plot 1: top left panel); **ii)** the number of new cases per day in South Africa, by province (Plot 2: top right panel); **iii)** the cumulative number of cases in South Africa and some other countries, (Plot 3: 2nd row left panel); **iv)** the cumulative number of deaths in South Africa and some other countries (Plot 4: 2nd row right panel); **v)** daily number of tests, with daily number of cases overlaid (Plot 5: 3rd row left panel); **vi)** Percentage of daily tests that are positive (Plot 6: 3rd row right panel); **vii)** Doubling time (cases) each week (Plot 7: 4th row left panel); and **viii)** the cumulative number of deaths in the South Africa, by province (Plot 8: 4th row right panel).<br><br>**Note:**<br>- Selection bias means that these data in no way reflect the prevalence of the disease.<br>- Because testing capacities and testing strategies differ between countries, direct comparisons between countries is fraught.<br>- No provincial breakdown of the number of cases on: 2020-03-27, 2020-04-07<br>- No data on the number of tests completed on: 2020-03-25, 2020-04-07 (took mid-point between 2020-04-06 and 2020-04-08).

Row
----------

### Total cases

```{r}
if(data$date[[nrow(data)]] == Sys.Date()) {
  cases <- data %>% 
    filter(date == Sys.Date()) %>% 
    summarise(total = sum(n_cases, na.rm = TRUE)) %>%
    .$total
} else {
  cases <- data %>% 
    filter(date == Sys.Date() - 1) %>% 
    summarise(total = sum(n_cases, na.rm = TRUE)) %>%
    .$total
}

valueBox(cases, 
         icon = "fa-stethoscope")
```

### Compound daily growth

```{r}
rate <- data %>% 
  group_by(date) %>% 
  summarise(total = sum(n_cases, na.rm = TRUE))

time_period = 1/(nrow(rate) - 1)
first_value = first(rate$total)
last_value = last(rate$total)

cdgr <- round(100 * (((last_value / first_value)^time_period) -1))

valueBox(paste0(cdgr, '%'), 
         icon = "fa-chart-line")

```

### Total deaths

```{r}
if(data$date[[nrow(data)]] == Sys.Date()) {
  deaths <- data %>% 
    filter(date == Sys.Date()) %>% 
    summarise(total = sum(n_deaths, na.rm = TRUE)) %>%
    .$total
} else {
  deaths <- data %>% 
    filter(date == Sys.Date() - 1) %>% 
    summarise(total = sum(n_deaths, na.rm = TRUE)) %>%
    .$total
}

valueBox(deaths, 
         icon = "fa-sad-tear", 
         color = "#CC0000")
```

### Total recoveries

```{r}
recover <- recover_jhu %>%
  filter(`Country/Region` == 'South Africa') %>% 
  select(-c(1:4)) %>% 
  select(ncol(.)) %>% 
  .[[1]]

valueBox(recover, 
         icon = "fa-smile", 
         color = "green")
```

### Total tests

```{r}
if(data$date[[nrow(data)]] == Sys.Date()) {
  tests <- data %>% 
    filter(date == Sys.Date()) %>% 
    .$n_tests %>% 
    unique(.)
} else {
  tests <- data %>% 
    filter(date == Sys.Date() - 1) %>% 
    .$n_tests %>% 
    unique(.)
}

valueBox(tests, 
         icon = "fa-notes-medical")
```

Row
----------

### Plot 1: Cumulative number of cases over time

```{r}
# Calculate total cases per date
data_totals <- data %>% 
    group_by(date) %>% 
    summarise(total = sum(n_cases, na.rm = TRUE)) 

## Fix dates with missing 'unknown' row
unknown_missing <- data %>% 
  filter(date < as_date('2020-03-23')) %>% 
  add_row(date = as_date('2020-03-22'),
          provinces = 'Unknown',
          n_tests = NA,
          n_cases = NA,
          n_deaths = NA,
          n_recoveries = NA) %>% 
  left_join(data_totals) %>% 
  complete(date, provinces, fill = list(n_cases = 0, 
                                        n_deaths = 0,
                                        n_recoveries = 0)) %>% 
  fill(n_tests, total, .direction = 'down') %>% 
  select(date, provinces, n_cases, total) %>% 
    pivot_wider(names_from = 'provinces',
                values_from = 'n_cases') 

## Get dates with 'unknown' row
unknown_present <- data %>% 
  filter(date > as_date('2020-03-22')) %>% 
  left_join(data_totals) %>% 
  select(date, provinces, n_cases, total) %>% 
    pivot_wider(names_from = 'provinces',
                values_from = 'n_cases') 

## Combine the two dataframes
data_cases_wide <- bind_rows(unknown_missing, unknown_present)

# Plot the data using plotly
## (damn I hate plotly's api)
data_cases_wide %>%     
    plot_ly(x = ~date, 
            y = ~total, 
            name = 'Total',
            type = 'scatter', 
            mode = 'lines+markers',
            marker = list(size = 10),
            hovertemplate = paste("<b>Date: </b>%{x}<br><b>Cases: <b>%{y}")) %>% 
    layout(font = list(family = 'Arial'),
           xaxis = list(title = 'Date',
                        titlefont = list(size = 20), 
                        nticks = nrow(data_cases_wide)),
           yaxis = list(title = 'Cumulative number of cases',
                        titlefont = list(size = 20))) %>% 
    add_trace(y = ~EC, name = 'Eastern Cape', 
              visible = 'legendonly') %>% 
    add_trace(y = ~FS, name = 'Free State', 
              visible = 'legendonly') %>% 
    add_trace(y = ~GP, name = 'Gauteng', 
              visible = 'legendonly') %>% 
    add_trace(y = ~KZN, name = 'KwaZulu-Natal',
              visible = 'legendonly') %>% 
    add_trace(y = ~LP, name = 'Limpopo', 
              visible = 'legendonly') %>% 
    add_trace(y = ~MP, name = 'Mpumalanga', 
              visible = 'legendonly') %>% 
    add_trace(y = ~NW, name = 'North West', 
              visible = 'legendonly') %>% 
    add_trace(y = ~NC, name = 'Northern Cape', 
              visible = 'legendonly') %>% 
    add_trace(y = ~WC, name = 'Western Cape', 
              visible = 'legendonly') %>% 
    add_trace(y = ~Unknown, name = 'Unknown', 
              visible = 'legendonly')
```

### Plot 2: Daily count of new cases, by province {.no-padding}

```{r}
# Read shape file
za_map <- st_read('data-shp/zaf_admin1.shp', quiet = TRUE)

# Simplify shapefile to a manageable size
za_map <- za_map %>%
    # Select columns
    select(ADM1_ID) %>%
    # Reduce size
    st_simplify(dTolerance = 0.03) 

# Simplify data to latest date
data_map <- data %>% 
  filter(date == max(date)) 

# Fix za_map admin_ID column
za_map <- za_map %>% 
  rename(provinces = ADM1_ID) %>% 
  mutate(provinces = as.character(provinces)) %>% 
  mutate(provinces = case_when(
    provinces == 'LIM' ~ 'LP',
    provinces == 'GT' ~ 'GP',
    TRUE ~ provinces
  )) %>% 
  # Join with map data
  left_join(data_map) %>% 
  arrange(provinces)

# Process data
za_map <- za_map %>% 
  # Filter out unknown
  filter(provinces != 'Unknown') %>% 
  # Add full province names
  mutate(province_names = case_when(
    provinces == 'WC' ~ 'Western Cape',
    provinces == 'EC' ~ 'Eastern Cape',
    provinces == 'NC' ~ 'Northern Cape',
    provinces == 'FS' ~ 'Free State',
    provinces == 'KZN' ~ 'KwaZulu-Natal',
    provinces == 'NW' ~ 'North West',
    provinces == 'GP' ~ 'Gauteng',
    provinces == 'MP' ~ 'Mpumalanga',
    provinces == 'LP' ~ 'Limpopo'
  )) 

date_past <- data %>% 
  filter(date != max(date)) %>% 
  filter(date == max(date)) %>% 
  arrange(provinces) %>% 
  select(provinces, n_cases) %>% 
  rename(n_cases24 = n_cases)

za_map <- za_map %>% 
  arrange(provinces) %>% 
  left_join(date_past) %>% 
  mutate(delta_cases = n_cases - n_cases24) %>% 
  # Add a tooltip
  mutate(tooltip = paste0('<b>', province_names, '</b><br>',
                          '<em>New cases: </em>', delta_cases, '<br>'))

# Generate plot object
gg_province <- ggplot(data = za_map) +
    geom_sf_interactive(aes(tooltip = tooltip,
                            fill = delta_cases), 
             color = '#000000',
             size = 0.25) +
    labs(title = str_glue('Date: {data$date[[nrow(data)]]}'),
         subtitle = 'Move cursor over each province to see province-specific data\nGrey fill indicates no data available') +
    scale_fill_distiller(name = 'New cases', 
                         direction = 1) +
    theme_void() +
    theme(panel.grid = element_line(colour = '#FFFFFF'),
          plot.caption = element_text(face = 'italic',
                                      hjust = 0))

girafe(ggobj = gg_province,
       options = list(opts_hover(css = 'cursor:pointer;fill:#FFFFFF;stroke:#FFFFFF;'),
                      opts_tooltip(css = 'background-color:#000000;font-family:sans-serif,arial;font-size:80%;color:#FFFFFF;padding:10px;border-radius:10px 10px 10px 10px;'),
                      opts_sizing(width = 0.67)))
```

Row
----------

### Plot 3: Cumulative cases (days since 100th case)

```{r}
# Select and filter data
data_jhu2 <- data_jhu %>% 
  rename(country = `Country/Region`) %>% 
  select(-Lat, -Long) %>% 
  filter(country %in% c('China', 'US', 'Brazil', 'France', 'Sweden', 'Denmark',
                        'Netherlands', 'Australia', 'New Zealand', 'Canada',
                        'United Kingdom', 'Italy', 'South Africa'))

# Process data
## The Netherlands
jhu_ned2 <- data_jhu2 %>% 
  filter(country == 'Netherlands' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'ned_count') %>% 
  filter(ned_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, ned_count)

## Australia
jhu_aus2 <- data_jhu2 %>% 
  filter(country == 'Australia') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'Australia') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'australia_count') %>% 
  filter(australia_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, australia_count)

## Canada
jhu_canada2 <- data_jhu2 %>% 
  filter(country == 'Canada') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'Canada') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'canada_count') %>% 
  filter(canada_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, canada_count)

## New Zealand
jhu_nz2 <- data_jhu2 %>% 
  filter(country == 'New Zealand' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'nz_count') %>% 
  filter(nz_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, nz_count)

## China
jhu_china2 <- data_jhu2 %>% 
  filter(country == 'China') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'China') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'china_count') %>% 
  filter(china_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, china_count)

## USA
jhu_us2 <- data_jhu2 %>% 
  filter(country == 'US') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'US') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'us_count') %>%
  filter(us_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, us_count)

## Brazil
jhu_brazil2 <- data_jhu2 %>% 
  filter(country == 'Brazil') %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'brazil_count') %>% 
  filter(brazil_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, brazil_count)

## France
jhu_france2 <- data_jhu2 %>% 
  filter(country == 'France') %>% 
  filter(is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'france_count') %>% 
  filter(france_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, france_count)

## United Kingdom
jhu_uk2 <- data_jhu2 %>% 
  filter(country == 'United Kingdom') %>% 
  filter(is.na(`Province/State`)) %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'uk_count') %>% 
  filter(uk_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, uk_count)

## Italy
jhu_italy2 <- data_jhu2 %>% 
  filter(country == 'Italy') %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'italy_count') %>% 
  filter(italy_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, italy_count)

## South Africa
jhu_za2 <- data_jhu2 %>% 
  filter(country == 'South Africa') %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'za_count') %>% 
  filter(za_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, za_count)

## Sweden
jhu_sweden2 <- data_jhu2 %>% 
  filter(country == 'Sweden') %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'sweden_count') %>% 
  filter(sweden_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, sweden_count)

## Denmark
jhu_denmark2 <- data_jhu2 %>% 
  filter(country == 'Denmark' & is.na(`Province/State`)) %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2)-1),
               names_to = 'date',
               values_to = 'denmark_count') %>% 
  filter(denmark_count > 95) %>% 
  mutate(days = row_number()) %>%
  select(days, denmark_count)

# Bind columns
data_jhu3 <- jhu_china2 %>% 
  left_join(jhu_italy2) %>% 
  left_join(jhu_us2) %>% 
  left_join(jhu_brazil2) %>% 
  left_join(jhu_denmark2) %>% 
  left_join(jhu_france2) %>% 
  left_join(jhu_nz2) %>% 
  left_join(jhu_uk2) %>% 
  left_join(jhu_aus2) %>% 
  left_join(jhu_ned2) %>% 
  left_join(jhu_za2) %>% 
  left_join(jhu_sweden2) %>% 
  left_join(jhu_canada2)

# Plot
plot_ly(data = data_jhu3,
        x = ~days,
        y = ~za_count,
        name = 'South Africa',
        type = 'scatter',
        marker = list(size = 0),
        mode = 'lines+markers',
        hovertemplate = paste("<b>Days since 100th case: </b>%{x}<br><b>Cases: <b>%{y}")) %>% 
    layout(font = list(family = 'Arial'),
           xaxis = list(title = 'Days since 100th case',
                        titlefont = list(size = 20)),
           yaxis = list(type = 'log',
                        title = 'Cumulative cases (log10)',
                        titlefont = list(size = 20))) %>% 
  add_trace(y = ~australia_count,
            name = 'Australia',
            visible = 'legendonly') %>% 
  add_trace(y = ~brazil_count,
            name = 'Brazil',
            visible = 'legendonly') %>% 
  add_trace(y = ~canada_count,
            name = 'Canada',
            visible = 'legendonly') %>% 
  add_trace(y = ~denmark_count,
            name = 'Denmark',
            visible = 'legendonly') %>% 
  add_trace(y = ~france_count,
            name = 'France',
            visible = 'legendonly') %>% 
  add_trace(y = ~italy_count,
            name = 'Italy',
            visible = 'legendonly') %>% 
  add_trace(y = ~ned_count,
            name = 'Netherlands',
            visible = 'legendonly') %>% 
  add_trace(y = ~nz_count,
            name = 'New Zealand',
            visible = 'legendonly') %>%
  add_trace(y = ~sweden_count,
            name = 'Sweden',
            visible = 'legendonly') %>%
  add_trace(y = ~uk_count,
            name = 'UK',
            visible = 'legendonly') %>% 
  add_trace(y = ~us_count,
            name = 'USA',
            visible = 'legendonly')
```

### Plot 4: Cumulative deaths (days since 100th case)

```{r}
deaths_jhu <- deaths_jhu %>% 
  rename(country = `Country/Region`) %>% 
  select(-Lat, -Long) %>% 
  filter(country %in% c('China', 'US', 'Brazil', 'France', 'Sweden', 'Denmark',
                        'Netherlands', 'Australia', 'New Zealand', 'Canada',
                        'United Kingdom', 'Italy', 'South Africa'))

# Process data
## The Netherlands
deaths_ned <- deaths_jhu %>% 
  filter(country == 'Netherlands' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'ned_deaths') 

cases_ned <- data_jhu2 %>% 
  filter(country == 'Netherlands' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'ned_cases') 

ned <- left_join(deaths_ned, cases_ned) %>% 
  filter(ned_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, ned_deaths)
  
## Australia
deaths_aus <- deaths_jhu %>% 
  filter(country == 'Australia') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'Australia') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'aus_deaths') 

cases_aus <- data_jhu2 %>% 
  filter(country == 'Australia') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'Australia') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'aus_cases') 

aus <- left_join(deaths_aus, cases_aus) %>% 
  filter(aus_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, aus_deaths)

## Canada
deaths_can <- deaths_jhu %>% 
  filter(country == 'Canada') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'Canada') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'can_deaths') 

cases_can <- data_jhu2 %>% 
  filter(country == 'Canada') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'Canada') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'can_cases') 

can <- left_join(deaths_can, cases_can) %>% 
  filter(can_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, can_deaths)

## New Zealand
deaths_nz <- deaths_jhu %>% 
  filter(country == 'New Zealand' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'nz_deaths') 

cases_nz <- data_jhu2 %>% 
  filter(country == 'New Zealand' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'nz_cases') 

nz <- left_join(deaths_nz, cases_nz) %>% 
  filter(nz_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, nz_deaths)
  
## China
deaths_china <- deaths_jhu %>% 
  filter(country == 'China') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'China') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'china_deaths') 

cases_china <- data_jhu2 %>% 
  filter(country == 'China') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'China') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'china_cases') 

china <- left_join(deaths_china, cases_china) %>% 
  filter(china_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, china_deaths)

## USA
deaths_us <- deaths_jhu %>% 
  filter(country == 'US' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'us_deaths') 

cases_us <- data_jhu2 %>% 
  filter(country == 'US' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'us_cases') 

us <- left_join(deaths_us, cases_us) %>% 
  filter(us_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, us_deaths)

## Brazil
deaths_bz <- deaths_jhu %>% 
  filter(country == 'Brazil' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'bz_deaths') 

cases_bz <- data_jhu2 %>% 
  filter(country == 'Brazil' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'bz_cases') 

bz <- left_join(deaths_bz, cases_bz) %>% 
  filter(bz_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, bz_deaths)

## France
deaths_fr <- deaths_jhu %>% 
  filter(country == 'France' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'fr_deaths') 

cases_fr <- data_jhu2 %>% 
  filter(country == 'France' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'fr_cases') 

fr <- left_join(deaths_fr, cases_fr) %>% 
  filter(fr_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, fr_deaths)

## United Kingdom
deaths_uk <- deaths_jhu %>% 
  filter(country == 'United Kingdom' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'uk_deaths') 

cases_uk <- data_jhu2 %>% 
  filter(country == 'United Kingdom' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'uk_cases') 

uk <- left_join(deaths_uk, cases_uk) %>% 
  filter(uk_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, uk_deaths)

## Italy
deaths_it <- deaths_jhu %>% 
  filter(country == 'Italy' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'it_deaths') 

cases_it <- data_jhu2 %>% 
  filter(country == 'Italy' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'it_cases') 

it <- left_join(deaths_it, cases_it) %>% 
  filter(it_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, it_deaths)

## South Africa
deaths_za <- deaths_jhu %>% 
  filter(country == 'South Africa' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'za_deaths') 

cases_za <- data_jhu2 %>% 
  filter(country == 'South Africa' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'za_cases') 

za <- left_join(deaths_za, cases_za) %>% 
  filter(za_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, za_deaths)

## Sweden
deaths_sw <- deaths_jhu %>% 
  filter(country == 'Sweden' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'sw_deaths') 

cases_sw <- data_jhu2 %>% 
  filter(country == 'Sweden' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'sw_cases') 

sw <- left_join(deaths_sw, cases_sw) %>% 
  filter(sw_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, sw_deaths)

## Denmark
deaths_dm <- deaths_jhu %>% 
  filter(country == 'Denmark' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(deaths_jhu) - 1),
               names_to = 'date',
               values_to = 'dm_deaths') 

cases_dm <- data_jhu2 %>% 
  filter(country == 'Denmark' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu2) - 1),
               names_to = 'date',
               values_to = 'dm_cases') 

dm <- left_join(deaths_dm, cases_dm) %>% 
  filter(dm_cases > 95) %>% 
  mutate(days = row_number()) %>% 
  select(days, dm_deaths)

# Bind columns
deaths_jhu2 <- china %>% 
  left_join(it) %>% 
  left_join(us) %>% 
  left_join(bz) %>% 
  left_join(dm) %>% 
  left_join(fr) %>% 
  left_join(nz) %>% 
  left_join(uk) %>% 
  left_join(aus) %>% 
  left_join(ned) %>% 
  left_join(za) %>% 
  left_join(sw) %>% 
  left_join(can)

# Plot
plot_ly(data = deaths_jhu2,
        x = ~days,
        y = ~za_deaths,
        name = 'South Africa',
        type = 'scatter',
        marker = list(size = 0),
        mode = 'lines+markers',
        hovertemplate = paste("<b>Days since 100th case: </b>%{x}<br><b>Deaths: <b>%{y}")) %>% 
    layout(font = list(family = 'Arial'),
           xaxis = list(title = 'Days since 100th case',
                        titlefont = list(size = 20)),
           yaxis = list(type = 'log',
                        title = 'Cumulative deaths (log10)',
                        titlefont = list(size = 20))) %>% 
  add_trace(y = ~aus_deaths,
            name = 'Australia',
            visible = 'legendonly') %>% 
  add_trace(y = ~bz_deaths,
            name = 'Brazil',
            visible = 'legendonly') %>%
  add_trace(y = ~can_deaths,
            name = 'Canada',
            visible = 'legendonly') %>% 
  add_trace(y = ~dm_deaths,
            name = 'Denmark',
            visible = 'legendonly') %>% 
  add_trace(y = ~fr_deaths,
            name = 'France',
            visible = 'legendonly') %>% 
  add_trace(y = ~it_deaths,
            name = 'Italy',
            visible = 'legendonly') %>% 
  add_trace(y = ~ned_deaths,
            name = 'Netherlands',
            visible = 'legendonly') %>% 
  add_trace(y = ~nz_deaths,
            name = 'New Zealand',
            visible = 'legendonly') %>%
  add_trace(y = ~sw_deaths,
            name = 'Sweden',
            visible = 'legendonly') %>%
  add_trace(y = ~uk_deaths,
            name = 'UK',
            visible = 'legendonly') %>% 
  add_trace(y = ~us_deaths,
            name = 'USA',
            visible = 'legendonly')
```

Row
----

### Plot 5: Daily number of tests (with overlay of daily number of cases)

```{r}
# Get cumulative case # and test # data for each date
tests <- data %>% 
  select(date, n_tests) %>% 
  distinct() %>% 
  mutate(tests_difference = n_tests - lag(n_tests)) %>% 
  mutate(tests_difference = ifelse(tests_difference == 0,
                                   yes = NA,
                                   no = tests_difference))

cases <- data %>% 
  group_by(date) %>% 
  summarise(total = sum(n_cases, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(cases_difference = total - lag(total))
  

# Join the two dataframes
cases_tests <- left_join(tests, cases) %>% 
  select(-n_tests, -total)

# Plot
plot_ly(data = cases_tests) %>% 
  add_trace(x = ~date,
            y = ~tests_difference,
            type = 'bar',
            name = 'Tests',
            hovertemplate = paste("<b>Date: </b>%{x}<br><b>Tests: <b>%{y}")) %>% 
  add_trace(x = ~date,
            y = ~cases_difference,
            type = 'scatter',
            mode = 'lines+markers',
            yaxis = 'y2',
            marker = list(size = 10),
            name = 'Cases', 
            hovertemplate = paste("<b>Date: </b>%{x}<br><b>Cases: <b>%{y}")) %>% 
  layout(font = list(family = 'Arial'),
         xaxis = list(title = 'Date',
                      titlefont = list(size = 20)),
         yaxis = list(side = 'left',
                      title = 'Daily tests',
                      titlefont = list(size = 20),
                      showgrid = FALSE,
                      zeroline = FALSE),
         yaxis2 = list(side = 'right',
                       title = 'Daily cases',
                       titlefont = list(size = 20),
                       overlaying = 'y',
                       showgrid = FALSE,
                       zeroline = FALSE))
```

### Plot 6: Percentage of daily tests that are positive

```{r}
# Get cumulative case # and test # data for each date
tests <- data %>% 
  select(date, n_tests) %>% 
  distinct() %>% 
  mutate(tests_difference = n_tests - lag(n_tests)) %>% 
  mutate(tests_difference = ifelse(tests_difference == 0,
                                   yes = NA,
                                   no = tests_difference))

cases <- data %>% 
  group_by(date) %>% 
  summarise(total = sum(n_cases, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(cases_difference = total - lag(total))
  

# Join the two dataframes
cases_tests <- left_join(tests, cases) %>% 
  select(-n_tests, -total)

# Calculate proportion of total tests that result in cases being detected
cases_tests <- cases_tests %>% 
  mutate(perc = round(100 * (cases_difference / tests_difference), 1))

# Plot
plot_ly(data = cases_tests,
       x = ~date,
       y = ~perc,
       type = 'bar', 
       name = 'Cases', 
       hovertemplate = paste("<b>Date: </b>%{x}<br><b>Percent +: <b>%{y}"),
       marker = list(color = 'rgb(49,130,189)',
                     size = 10)) %>% 
  layout(font = list(family = 'Arial'),
           xaxis = list(title = 'Date',
                        titlefont = list(size = 20)),
           yaxis = list(title = 'Daily tests that are positive (%)',
                        titlefont = list(size = 20)))
```

Row
----

### Plot 7: Doubling time for cases (in days) for each week

```{r}
double <- data %>% 
  select(date, n_cases) %>% 
  group_by(date) %>% 
  summarise(total = sum(n_cases, na.rm = TRUE)) %>% 
  mutate(week = week(date)) %>% 
  group_by(week) %>% 
  nest() %>% 
  mutate(periods = map(.x = data,
                      ~ 1 / (nrow(.x) - 1)),
         first = map(.x = data,
                     ~ first(.x$total)),
         last = map(.x = data,
                    ~ last(.x$total)),
         compound_growth_rate = pmap(.l = list(periods, first,last),
                                     ~ (((..3 / ..2)^..1) - 1)),
         double_time = map(.x = compound_growth_rate,
                           ~ log(2) / .x)) %>% 
  unnest(double_time) %>%
  ungroup() %>% 
  select(week, double_time) %>% 
  mutate(week = as.character(dense_rank(week)),
         double_time = round(double_time, 2))


plot_ly(data = double,
       x = ~week,
       y = ~double_time,
       type = 'bar', 
       name = 'Cases', 
       hovertemplate = paste("<b>Week: </b>%{x}<br><b>Doubling time (days): <b>%{y}"),
       marker = list(color = 'rgb(49,130,189)',
                     size = 10)) %>% 
  layout(font = list(family = 'Arial'),
           xaxis = list(title = 'Week',
                        titlefont = list(size = 20)),
           yaxis = list(title = 'Doubling time (days)',
                        titlefont = list(size = 20)))

```

### Plot 8: Cumulative deaths, by province

```{r}
# Edit za_map
za_map2 <- za_map %>% 
  # Add new tooltip
  mutate(tooltip2 = paste0('<b>', province_names, '</b><br>',
                           '<em>Number of deaths: </em>', n_deaths, '<br>'))

# Generate plot object
gg_province2 <- ggplot(data = za_map2) +
    geom_sf_interactive(aes(tooltip = tooltip2,
                            fill = n_deaths), 
             color = '#000000',
             size = 0.25) +
    labs(title = str_glue('Date: {data$date[[nrow(data)]]}'),
         subtitle = 'Move cursor over each province to see province-specific data\nGrey fill indicates no data available') +
    scale_fill_distiller(name = 'Deaths', 
                         palette = 'YlOrRd',
                         direction = 1) +
    theme_void() +
    theme(panel.grid = element_line(colour = '#FFFFFF'),
          plot.caption = element_text(face = 'italic',
                                      hjust = 0))

girafe(ggobj = gg_province2,
       options = list(opts_hover(css = 'cursor:pointer;fill:#FFFFFF;stroke:#FFFFFF;'),
                      opts_tooltip(css = 'background-color:#000000;font-family:sans-serif,arial;font-size:80%;color:#FFFFFF;padding:10px;border-radius:10px 10px 10px 10px;'),
                      opts_sizing(width = 0.67)))
```

```{r, eval = FALSE}
### Plot 3: Cases per 100,000 population (days since cases > 1/100,000 people)

# Select and filter data
data_jhu <- data_jhu %>% 
  rename(country = `Country/Region`) %>% 
  select(-Lat, -Long) %>% 
  filter(country %in% c('China', 'US', 'Brazil', 'France', 'Sweden', 'Denmark',
                        'Netherlands', 'Australia', 'New Zealand', 
                        'United Kingdom', 'Italy', 'South Africa'))

# Process data
## The Netherlands
jhu_netherlands <- data_jhu %>% 
  filter(country == 'Netherlands' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'ned_count') %>% 
  mutate(cum_sum = cumsum(ned_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(ned_count.100k = (ned_count / 17125596) * 100000) %>% 
  filter(ned_count.100k >= 1) %>% 
  mutate(days = row_number()) %>%
  select(date, days, ned_count, ned_count.100k) %>% 
  mutate(ned_count.100k = round(ned_count.100k, 4)) %>% 
  select(-date)

## Australia
jhu_australia <- data_jhu %>% 
  filter(country == 'Australia') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'Australia') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'australia_count') %>% 
  mutate(cum_sum = cumsum(australia_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(australia_count.100k = (australia_count / 25499884) * 100000) %>% 
  filter(australia_count.100k >= 1) %>% 
  mutate(days = row_number()) %>%
  select(date, days, australia_count, australia_count.100k) %>% 
  mutate(australia_count.100k = round(australia_count.100k, 4)) %>% 
  select(-date)

## New Zealand
jhu_nz <- data_jhu %>% 
  filter(country == 'New Zealand' & is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'nz_count') %>% 
  mutate(cum_sum = cumsum(nz_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(nz_count.100k = (nz_count / 4822233) * 100000) %>% 
  filter(nz_count.100k >= 1) %>% 
  mutate(days = row_number()) %>%
  select(date, days, nz_count, nz_count.100k) %>% 
  mutate(nz_count.100k = round(nz_count.100k, 4)) %>% 
  select(-date)

## China
jhu_china <- data_jhu %>% 
  filter(country == 'China') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'China') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'china_count') %>% 
  mutate(cum_sum = cumsum(china_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(china_count.100k = (china_count / 1439323766) * 100000) %>% 
  filter(china_count.100k >= 1) %>% 
  mutate(days = row_number()) %>%
  select(date, days, china_count, china_count.100k) %>% 
  mutate(china_count.100k = round(china_count.100k, 4)) %>% 
  select(-date)

## USA
jhu_us <- data_jhu %>% 
  filter(country == 'US') %>% 
  select(-`Province/State`) %>% 
  summarise_if(is.numeric, sum) %>% 
  mutate(country = 'US') %>% 
  select(country, everything())  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'us_count') %>%
  mutate(cum_sum = cumsum(us_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(us_count.100k = (us_count / 331002651) * 100000) %>% 
  filter(us_count.100k >= 1) %>% 
  mutate(days = row_number()) %>% 
  select(date, days, us_count, us_count.100k) %>% 
  mutate(us_count.100k = round(us_count.100k, 4)) %>% 
  select(-date)

## Brazil
jhu_brazil <- data_jhu %>% 
  filter(country == 'Brazil') %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'brazil_count') %>% 
  mutate(cum_sum = cumsum(brazil_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(brazil_count.100k = (brazil_count / 212559417) * 100000) %>% 
  filter(brazil_count.100k >= 1) %>% 
  mutate(days = row_number()) %>% 
  select(date, days, brazil_count, brazil_count.100k) %>% 
  mutate(brazil_count.100k = round(brazil_count.100k, 4)) %>% 
  select(-date)

## France
jhu_france <- data_jhu %>% 
  filter(country == 'France') %>% 
  filter(is.na(`Province/State`)) %>% 
  select(-`Province/State`) %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'france_count') %>% 
  mutate(cum_sum = cumsum(france_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(france_count.100k = (france_count / 65273511) * 100000) %>% 
  filter(france_count.100k >= 1) %>% 
  mutate(days = row_number()) %>% 
  select(date, days, france_count, france_count.100k) %>% 
  mutate(france_count.100k = round(france_count.100k, 4)) %>% 
  select(-date)

## United Kingdom
jhu_uk <- data_jhu %>% 
  filter(country == 'United Kingdom') %>% 
  filter(is.na(`Province/State`)) %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'uk_count') %>% 
  mutate(cum_sum = cumsum(uk_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>%  
  mutate(uk_count.100k = (uk_count / 67886011) * 100000) %>% 
  filter(uk_count.100k >= 1) %>% 
  mutate(days = row_number()) %>% 
  select(date, days, uk_count, uk_count.100k) %>% 
  mutate(uk_count.100k = round(uk_count.100k, 4)) %>% 
  select(-date)

## Italy
jhu_italy <- data_jhu %>% 
  filter(country == 'Italy') %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'italy_count') %>% 
  mutate(cum_sum = cumsum(italy_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>%  
  mutate(italy_count.100k = (italy_count / 60461826) * 100000) %>% 
  filter(italy_count.100k >= 1) %>% 
  mutate(days = row_number()) %>% 
  select(date, days, italy_count, italy_count.100k) %>% 
  mutate(italy_count.100k = round(italy_count.100k, 4)) %>% 
  select(-date)

## South Africa
jhu_za <- data_jhu %>% 
  filter(country == 'South Africa') %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'za_count') %>% 
  mutate(cum_sum = cumsum(za_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(za_count.100k = (za_count / 59308690) * 100000) %>% 
  filter(za_count.100k >= 1) %>% 
  mutate(days = row_number()) %>% 
  select(date, days, za_count, za_count.100k) %>% 
  mutate(za_count.100k = round(za_count.100k, 4)) %>% 
  select(-date)

## Sweden
jhu_sweden <- data_jhu %>% 
  filter(country == 'Sweden') %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'sweden_count') %>% 
  mutate(cum_sum = cumsum(sweden_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(sweden_count.100k = (sweden_count / 10099265) * 100000) %>% 
  filter(sweden_count.100k >= 1) %>% 
  mutate(days = row_number()) %>% 
  select(date, days, sweden_count, sweden_count.100k) %>% 
  mutate(sweden_count.100k = round(sweden_count.100k, 4)) %>% 
  select(-date)

## Denmark
jhu_denmark <- data_jhu %>% 
  filter(country == 'Denmark' & is.na(`Province/State`)) %>% 
  select(-`Province/State`)  %>% 
  pivot_longer(cols = 2:(ncol(data_jhu)-1),
               names_to = 'date',
               values_to = 'denmark_count') %>% 
  mutate(cum_sum = cumsum(denmark_count)) %>% 
  filter(cum_sum > 0) %>% 
  select(-cum_sum) %>% 
  mutate(denmark_count.100k = (denmark_count / 5787330) * 100000) %>% 
  filter(denmark_count.100k >= 1) %>% 
  mutate(days = row_number()) %>% 
  select(date, days, denmark_count, denmark_count.100k) %>% 
  mutate(denmark_count.100k = round(denmark_count.100k, 4)) %>% 
  select(-date)

# Bind columns
data_jhu2 <- jhu_italy %>% 
  left_join(jhu_us) %>% 
  left_join(jhu_brazil) %>% 
  left_join(jhu_denmark) %>% 
  left_join(jhu_france) %>% 
  left_join(jhu_nz) %>% 
  left_join(jhu_uk) %>% 
  left_join(jhu_australia) %>% 
  left_join(jhu_netherlands) %>% 
  left_join(jhu_za) %>% 
  left_join(jhu_sweden)

# Plot
plot_ly(data = data_jhu2,
        x = ~days,
        y = ~za_count.100k,
        name = 'South Africa',
        type = 'scatter',
        marker = list(size = 0),
        mode = 'lines+markers',
        hovertemplate = paste("<b>Days: </b>%{x}<br><b>Cases/100,000 pop: <b>%{y}")) %>% 
    layout(font = list(family = 'Arial'),
           xaxis = list(title = 'Days since cases > 1 per 100,000',
                        titlefont = list(size = 20)),
           yaxis = list(type = 'log',
                        title = 'Cumulative cases/100,000 people (log10)',
                        titlefont = list(size = 20))) %>% 
  add_trace(y = ~australia_count.100k,
            name = 'Australia',
            visible = 'legendonly') %>% 
  add_trace(y = ~brazil_count.100k,
            name = 'Brazil',
            visible = 'legendonly') %>% 
  add_trace(y = ~denmark_count.100k,
            name = 'Denmark',
            visible = 'legendonly') %>% 
  add_trace(y = ~france_count.100k,
            name = 'France',
            visible = 'legendonly') %>% 
  add_trace(y = ~italy_count.100k,
            name = 'Italy',
            visible = 'legendonly') %>% 
  add_trace(y = ~ned_count.100k,
            name = 'Netherlands',
            visible = 'legendonly') %>% 
  add_trace(y = ~nz_count.100k,
            name = 'New Zealand',
            visible = 'legendonly') %>%
  add_trace(y = ~sweden_count.100k,
            name = 'Sweden',
            visible = 'legendonly') %>%
  add_trace(y = ~uk_count.100k,
            name = 'UK',
            visible = 'legendonly') %>% 
  add_trace(y = ~us_count.100k,
            name = 'USA',
            visible = 'legendonly')
```

```{r eval = FALSE}
### Daily count of new cases and recoveries, for the country

# Calculate cumulative cases
data_daily <- data %>% 
  select(date, n_cases) %>% 
  group_by(date) %>% 
  summarise(n_cases = sum(n_cases, na.rm = TRUE)) %>% 
  ungroup()

# Top slice the first row of the cumulative cases data
top_slice <- data_daily %>% 
  filter(date == '2020-3-12') 

# Calculate daily new cases totals 
data_daily <- data_daily %>% 
  mutate(n_cases = n_cases - lag(n_cases)) %>% 
  filter(date != '2020-03-12') %>% 
  # Add back the top sliced data
  bind_rows(top_slice) %>% 
  arrange(date) %>% 
  mutate(date = as.Date(date))

# Process recover_jhu data
recover_jhu <- recover_jhu %>% 
  filter(`Country/Region` == 'South Africa') %>% 
  select(-c(1:4)) %>% 
  pivot_longer(cols = everything(),
               names_to = 'date',
               values_to = 'n_recoveries') %>% 
  mutate(date = mdy(date)) %>% 
  filter(date >= as.Date('2020-03-12')) %>% 
  mutate(n_recoveries = n_recoveries - lag(n_recoveries)) %>% 
  mutate(n_recoveries = ifelse(is.na(n_recoveries), 
                               yes = 0,
                               no = n_recoveries))

data_daily <- data_daily %>% 
  left_join(recover_jhu)

# Plot
plot_ly(data = data_daily,
       x = ~date,
       y = ~n_cases,
       type = 'bar', 
       name = 'Cases', 
       hovertemplate = paste("<b>Date: </b>%{x}<br><b>Cases: <b>%{y}"),
       marker = list(color = 'rgb(49,130,189)',
                     size = 10)) %>% 
  layout(font = list(family = 'Arial'),
           xaxis = list(title = 'Date',
                        titlefont = list(size = 20), 
                        nticks = nrow(data_daily)),
           yaxis = list(title = 'Daily count',
                        titlefont = list(size = 20))) %>% 
  add_trace(y = ~n_recoveries, 
            name = 'Recoveries', 
            hovertemplate = paste("<b>Date: </b>%{x}<br><b>Recoveries: <b>%{y}"),
            marker = list(color = 'rgb(204,204,204)'),
            visible = 'legendonly')
```


